language: ruby
sudo: false
rvm:
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - 2.6.1
  - jruby-9.1.10.0
  - jruby-9.2.7.0
gemfile:
  - Gemfile
  - Gemfile.rails-3.2
  - Gemfile.rails-4.2
  - Gemfile.rails-5.2
  - Gemfile.rails-6.0
matrix:
  exclude:
  - rvm: 2.3.8
    gemfile: Gemfile.rails-6.0
  - rvm: 2.4.5
    gemfile: Gemfile.rails-6.0
  - rvm: jruby-9.1.10.0
    gemfile: Gemfile.rails-6.0
